### ISSUE TITLE
Update "wp_all_import_is_post_to_create" hook reference

### ISSUE THREAD

**Issue by mbissett** [soflyy/wp-all-import-action-reference#12]
We adjusted the amount of parameters that are available in this hook. I've got this so far:

<pre>/**
 * ========================================
 * Filter: wp_all_import_is_post_to_create
 * ========================================
 *
 * Return a boolean indicating if the record should be imported. Note that
 * this is only for new posts. The "wp_all_import_is_post_to_update"
 * filter is for updating existing posts
 * 
 * @param $continue_import   bool (true = create, false = skip)
 * @param $data              array - An array holding values for the current record. If importing from
 *                                        XML, attributes can be accessed as SimpleXMLElement objects.
 * @param $import_id         int   - Import id. It can be used to make the code limited to a specific
 *                                        import only. 
 *
 * @return bool (true = create, false = skip)
 */
function my_is_post_to_create($continue_import, $data, $import_id)
{
    // your code here
    return true;
}
add_filter('wp_all_import_is_post_to_create', 'my_is_post_to_create', 10, 3);</pre>

But the example use has to be updated.

**Comment by trey8611** [comment]
I went ahead and updated this because I keep getting annoyed at not being able to link to it lol. Let me know if I missed anything.

**Comment by mbissett** [comment]
Looks good to me, thanks Trey! :)
