### ISSUE TITLE
Update "wp_all_import_is_post_to_update" hook reference

### ISSUE THREAD

**Issue by mbissett** [soflyy/wp-all-import-action-reference#13]
We adjusted the amount of parameters that are available in this hook. I've got this so far:

<pre>/**
 * =======================================
 * Filter: wp_all_import_is_post_to_update
 * =======================================
 *
 * Return a boolean indicating if the existing record should be updated. For
 * new posts see "wp_all_import_is_post_to_create"
 *
 * @param $continue_import bool (true = create, false = skip)
 * @param $post_id         int    - Post id
 * @param $data            array  - An array holding values for the current record. If importing from
 *                                       XML, attributes can be accessed as SimpleXMLElement objects.
 * @param $import_id       int    - Import id
 *
 * @return bool (true = update, false = skip)
 */
function my_is_post_to_update($continue_import, $post_id, $data, $import_id)
{
    // your code here
    return true;
}
add_filter('wp_all_import_is_post_to_update', 'my_is_post_to_update', 10, 4);</pre>

But the example use has to be updated.

**Comment by trey8611** [comment]
Went ahead and updated this as well while updating #12

**Comment by candlewickpress** [comment]
Does this require a change in the example code or will this still work?

`function is_post_to_update($postid) {
   $do_not_update = get_post_meta($postid, 'do_not_update', true);
   if ($do_not_update == true) {
		 return false;
	 }
	 return true;
}

add_filter('wp_all_import_is_post_to_update', 'is_post_to_update', 10, 4);`

**Comment by mbissett** [comment]
The example here on GitHub had been updated, but I do see that the examples on our site need to be updated, I've taken care of that now.

As for your snippet, it needs to be written like this:

<pre>function is_post_to_update($continue_import, $postid, $data, $import_id) {
   $do_not_update = get_post_meta($postid, 'do_not_update', true);
   if ($do_not_update == true) {
		 return false;
	 }
	 return true;
}

add_filter('wp_all_import_is_post_to_update', 'is_post_to_update', 10, 4);</pre>

**Comment by joeguilmette** [comment]
@mbissett feel free to close this out whenever it's completed.

**Comment by mbissett** [comment]
You're welcome @candlewickpress!
