### ISSUE TITLE
Document wp_all_export_generate_bundle

### ISSUE THREAD

**Issue by trey8611** [soflyy/wp-all-import-action-reference#15]
This filter can be used to prevent the bundle ZIP file from being generated. Example:

`add_filter('wp_all_export_generate_bundle', function(){
return false;
});`

**Comment by joeguilmette** [comment]
Out of curiosity, why would someone care about not creating the bundle?

**Comment by trey8611** [comment]
The 2 use cases I've seen are:

1) Intermittent server errors related to generating the zip file. The problem wasn't easy to reproduce and was totally random, but disabling the ZIP bundle file from being created fixed it.

2) User running an export and then a third party is extracting the file from their server. The ZIP file was causing confusion for the third party so they wanted to keep it from being generated.

**Comment by mbissett** [comment]
Documented here: https://github.com/soflyy/wp-all-import-action-reference/blob/master/all-export/wp_all_export_generate_bundle.php
