### ISSUE TITLE
wp_all_import_attachments_uploads_dir

### ISSUE THREAD

**Issue by mbissett** [soflyy/wp-all-import-action-reference#16]
It's the equivalent of the "wp_all_import_images_uploads_dir" hook, but it only applies to attachments uploaded via the "Download & Import Attachments" field in "Other Post Options".

**Comment by mbissett** [comment]
Done: https://github.com/soflyy/wp-all-import-action-reference/blob/master/all-import/wp_all_import_attachments_uploads_dir.php

**Comment by CuellarK** [comment]
Hi Michael,
Will you tell me the best way, or show me, to assign a subfolder for images importing as an attachment, please? I'm using a plugin that accesses 3D images from a subfolder under the default uploads folder. I'm importing .OBJ and .STL files to it and need to define the uploads folder. Got a second to help?

Thank you for your time,

Kendall

**Comment by joeguilmette** [comment]
Hi @CuellarK, sorry for the delay in getting back to you on this. We don't provide support via GitHub, but if you still need help you can submit a support ticket here: http://www.wpallimport.com/support/
