### ISSUE TITLE
Use import_id with pxmi_saved_post or pmxi_after_post_import 

### ISSUE THREAD

**Issue by ArchimidisM** [soflyy/wp-all-import-action-reference#17]
Dear wp all import team
is there currently a way of getting the import_id with the above mentioned hooks?

I am trying to do some MySQL stuff however I need the import id as well.

**Comment by trey8611** [comment]
Hey @ArchimidisM 

The 1st argument passed to your function in the pmxi_after_post_import hook is the import ID, and for pmxi_saved_post you can find the import ID using this code:

`$import_id = ( isset( $_GET['id'] ) ? $_GET['id'] : ( isset( $_GET['import_id'] ) ? $_GET['import_id'] : 'new' ) );`

**Comment by ArchimidisM** [comment]
Thanks a lot for your great help.

**Comment by ziodave** [comment]
> you can find the import ID using this code:
> 
> `$import_id = ( isset( $_GET['id'] ) ? $_GET['id'] : ( isset( $_GET['import_id'] ) ? $_GET['import_id'] : 'new' ) );`

This won't work in CLI though.

**Comment by Programmer095** [comment]
@ziodave use the `wp_all_import_get_import_id()` helper function to get the import ID instead. It should work in all cases.

**Comment by ziodave** [comment]
I can confirm it works.
