### ISSUE TITLE
Regarding limiting amount of posts to export

### ISSUE THREAD

**Issue by MarcusFuto** [soflyy/wp-all-import-action-reference#24]
I am exporting an XML feed of properties. 

I want to limit the number of properties to 200. I asked support and they gave me this:

```
function my_export_csv_rows($articles, $options, $export_id)
{
    // change 1 to your real export ID
	if($export_id == "1"):
		// change -1 to the number of records you want to export, this will start from the highest post ID and work backward
		// -1 = 1 record exported, -50 = 50 records exported
		$articles = array_slice($articles, -1);
    
        endif;

    	return $articles;
	
}
add_filter('wp_all_export_csv_rows', 'my_export_csv_rows', 10, 3);
```

However, I have read that wp_all_export_csv_rows is only for csv files. So I found this action reference for wp_all_export_xml_rows, but it seems to be structured totally differently. 

I am not very good at php, but maybe some good hearted soul could help me out.

**Comment by joeguilmette** [comment]
Hey Marcus, I just checked on your support request - Cory is still discussing with our developer. I'll reply to you over there where we can continue this discussion.
