### ISSUE TITLE
Is pmxi_saved_post called when action hooks are disabled?

### ISSUE THREAD

**Issue by kpu23** [soflyy/wp-all-import-action-reference#26]
Hey Soflyy team,

If an import has `do_action` calls disabled (i.e. Increase speed by disabling do_action calls in wp_insert_post during import.), will the action `pmxi_saved_post` be called?

Thank you,
Kevin.

**Comment by joeguilmette** [comment]
Hi @kpu23 I believe the answer is yes, but let's make sure and ask @cmdmcs.

**Comment by cmdmcs** [comment]
The `pmxi_saved_post` action will be called always during import process, even if `Increase speed by disabling do_action calls in wp_insert_post during import` option enabled.
