### ISSUE TITLE
wp_all_import_image_filename does not take args in wp-all-import-pro/classes/api.php

### ISSUE THREAD

**Issue by darenzammit** [soflyy/wp-all-import-action-reference#37]
The filter 'wp_all_import_image_filename' in wp-all-import-pro/classes/api.php should be renamed to be specific to PMXI_API::upload_image();

I came across a fatal error when trying to modify the image filename on an ACF image field since the filter 'wp_all_import_image_filename' passed in  PMXI_API::upload_image does not pass any arguments other than the image_name.

**Comment by joeguilmette** [comment]
@darenzammit - thanks! would it be possible to submit a bug report to support@wpallimport.com?
