### ISSUE TITLE
wp_all_import_variable_product_imported filter also triggered on with product_variations

### ISSUE THREAD

**Issue by thomasmery** [soflyy/wp-all-import-action-reference#4]
Hi there,

thanks a lot for this repo and examples

I'm trying to use _wp_all_import_variable_product_imported_

and would expect only _variable_ products to be passed in (with $parent_id)

but checking on `$product->get_type()` shows that variations are also passed to the callback

is that expected?

p.s. I'm using this config 

![image](https://cloud.githubusercontent.com/assets/1503822/25233327/c7ab1058-25de-11e7-8235-c77a3f54c0d0.png)

**Comment by trey8611** [comment]
Hi @thomasmery 

I'm looking into this issue as well and will let you know what I find out.

**Comment by trey8611** [comment]
@thomasmery this problem should be fixed in the latest beta of our WooCo add-on. It was related to this: https://github.com/soflyy/wp-all-import-action-reference/issues/6#issuecomment-300963453
