### ISSUE TITLE
import addon, character & in dropdown values

### ISSUE THREAD

**Issue by sandiwinter** [soflyy/wp-all-import-action-reference#44]
Hi,

When using character & in dropdown field value receiving error in js console:

Syntax error, unrecognized expression: .switcher-target-winter_listings_addoninput_4_1_Lease & Rent

http://prntscr.com/lb19pp

**Comment by joeguilmette** [comment]
Sorry, I don't understand the issue you're having. What are you trying to do when you encounter this error? How would we be able to reproduce it?

**Comment by sandiwinter** [comment]
Hi,

I created most basic example to simulate this:

http://prntscr.com/lbdo83

This part of code generate error:

http://prntscr.com/lbdopa

example code:

[wp-all-import-issue.zip](https://github.com/soflyy/wp-all-import-action-reference/files/2522730/wp-all-import-issue.zip)

step by step:

1. activate this "issue example" plugin and wpallimport

2. All import->new import

3. Upload a file (take any csv/xml file)

4. Create new posts

5. continue to step 3

and now issue is visible, you can't click on any tab because of js issue

Let me know if this helps?

**Comment by joeguilmette** [comment]
Hi Sandi, 

I was able to clear this up by changing the key from `A & B` to `A_and_B`:

![screen shot 2018-11-01 at 3 39 01 pm](https://user-images.githubusercontent.com/6581316/47841503-64534800-ddec-11e8-8585-4c35f5ad81d7.png)

**Comment by sandiwinter** [comment]
I know that A_and_B works, we don't have issue with that.

We need to save A & B example into database so key must stay A & B, but wpallimport should not crash in such case.

in my screenshot you can see that there is some javascript error in wpallimport what is source of issue and this should be solved: https://prnt.sc/lb19pp

Thanks

**Comment by joeguilmette** [comment]
> Or if you can suggest some better way to import A & B to database?

You can user `str_replace` to change `A_and_B` to `A & B`:
```
update_post_meta( $post_id, 'is_primary', str_replace("A_and_B","A & B",$data[ 'is_primary' ] ));
```

Here's an install where the code is up and running: http://misty-crocodile.w6.wpsandbox.pro/?upass=u2lhWVRqB270

And here's a post where the custom field is imported as `A & B`:
http://misty-crocodile.w6.wpsandbox.pro/wp-admin/post.php?post=41&action=edit

<img width="510" alt="screen shot 2018-11-04 at 4 31 19 pm" src="https://user-images.githubusercontent.com/6581316/47962429-15f1b380-e04f-11e8-8f7d-eede3063eb15.png">
