### ISSUE TITLE
pmxi_custom_field not triggered for product_variation of Product with a single Variation

### ISSUE THREAD

**Issue by thomasmery** [soflyy/wp-all-import-action-reference#5]
Hi,

I'm using this config

![image](https://cloud.githubusercontent.com/assets/1503822/25233430/144f0414-25df-11e7-93d3-d83cca70159e.png)

![image](https://cloud.githubusercontent.com/assets/1503822/25233515/52d9888a-25df-11e7-96a0-9a54f1ca7381.png)

and it seems like the _pmxi_custom_field_ is skipping the first variation when a Product has only one 
i.e. only 1 line in the csv file (so a Product + 1 Variation are created)

is that expected?

it's quite confusing imho

thanks a lot

**Comment by trey8611** [comment]
Hey @thomasmery 

I see what you mean. I'm looking into this now and will let you know what I find out.

**Comment by trey8611** [comment]
Hey @thomasmery 

I'm very sorry for not getting back to you on this. We fixed this issue in the latest release. Let us know if you're still having issues.

**Comment by thomasmery** [comment]
Hey @trey8611 

old stuff for me now ;)

I might get back into the project  and see how it behaves

I'll close for now as you seem to say it's fixed

thanks
thomas

**Comment by thomasmery** [comment]
Hi there,

just sent a ticket about this via the support form on the site,

I did not aven remember this issue existed here :(

so as far as I can tell this is not fixed: first variation does not get the custom fields values but parent product does

WPAI 4.5.1
WPAI WC 2.3.9

thanks
