### ISSUE TITLE
wp_all_import_images_uploads_dir does not pass $import_id

### ISSUE THREAD

**Issue by bransinanderson** [soflyy/wp-all-import-action-reference#55]
I have a condition that checks for a specific import ID. The issue is that wp_all_import_images_uploads_dir triggers a number of times without $import_id being passed every time, causing my conditional check to fail for import ID 34.

My wpai_set_upload_folder_by_post_date function seems to run 3 times, the path of directory is incorrect because $import_id argument is not passed every time.

WordPress Version 5.1
WP All Import Pro Version 4.5.6
WP All Import - ACF Add-On Version 3.2.1-beta-1.4

```
function wpai_set_upload_folder_by_post_date($uploads, $postData, $current_xml_node, $import_id) {

	if ( ! empty($postData['post_date'])) {
		$protected_folder_name = 'protected';

		$uploads['path'] = $uploads['basedir'] . '/' . date("Y/m", strtotime($postData['post_date']));
		$uploads['url'] = $uploads['baseurl'] . '/' . date("Y/m", strtotime($postData['post_date']));

		// import 34 is the specific import where we handle the protected directory
		// it appears removing the condition for $import_id it will work properly
		if ($postData['post_type'] == 'my_custom_post_type' && $import_id == "34") {
			$uploads['path'] = str_replace('uploads', 'uploads/' . $protected_folder_name, $uploads['path']);
			$uploads['url'] = str_replace('uploads', 'uploads/' . $protected_folder_name, $uploads['url']);
		}

		if (!file_exists($uploads['path'])) {
			mkdir($uploads['path'], 0755, true);
		}
		
	}

	return $uploads;

}
add_filter('wp_all_import_images_uploads_dir', 'wpai_set_upload_folder_by_post_date', 10, 4);
```

**Comment by trey8611** [comment]
Hi @bransinanderson 

Thanks for the report - I can see the problem and I've reported it to our developer. We will be releasing a fix in a new BETA version of WP All Import soon, but in the meantime you can use the following code within your function to get the correct import ID every time:

```php
$import_id = ( isset( $_GET['id'] ) ? $_GET['id'] : ( isset( $_GET['import_id'] ) ? $_GET['import_id'] : 'new' ) );
```
