### ISSUE TITLE
Your server terminated the import process

### ISSUE THREAD

**Issue by muprabakaran91** [soflyy/wp-all-import-action-reference#57]
When ever i upload the products from wp import all getting error i have aws provider they told me nothing issues in my side and i'm not able to predict what is the issues can help me issues below 

Your server terminated the import process
Ask your host to check your server's error log. They will be able to determine why your server is terminating the import process.

error screen shot --https://ibb.co/gRnXx0p

i not able to bulk upload on products showing error on server terminate the process kindly contact the hosting provider error message..   
{"code":"internal_server_error","message":"The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.","data":{"status":500},"additional_errors":[]}

**Comment by mbissett** [comment]
I'm sorry, but we only handle support over at: http://www.wpallimport.com/support/

Closing this issue out.
