### ISSUE TITLE
wp_all_import_variable_product_imported filter triggered multiple times for same parent product

### ISSUE THREAD

**Issue by thomasmery** [soflyy/wp-all-import-action-reference#6]
Hi,

As I was debugging it appeared that the _wp_all_import_variable_product_imported_ filter was triggered multiple time for the same _$post_parent_

is it expected?

thanks

**Comment by trey8611** [comment]
Hi @thomasmery 

If you're saving multiple variations to the same parent product, then yes it would make sense for the hook to trigger multiple times and return the same post parent ID.

**Comment by thomasmery** [comment]
Hi @trey8611 

thanks for taking the time

what confuses me is that given the example

https://github.com/soflyy/wp-all-import-action-reference/blob/master/all-import/wp_all_import_variable_product_imported.php

I would not expect this to be triggered each time a variation is saved but only once for the _variable_ product

so that I can loop through the variations only once

but as I said, I'm confused so maybe it's the way it should be

**Comment by trey8611** [comment]
Hey @thomasmery 

Yeah - in looking at this again, I would agree with you. Sorry for the confusion. I'm going to check with our developer about this to clear things up and I'll update you as soon as possible.

**Comment by trey8611** [comment]
@thomasmery this was a bug, our developer fixed it and released a new beta version of our WooCommerce add-on. You can download it here: http://www.wpallimport.com/portal/

**Comment by thomasmery** [comment]
thanks Trey,

I'll test it out when I have the time
