### ISSUE TITLE
pmxi_delete_post delete post not triggered

### ISSUE THREAD

**Issue by zoltan-ofir** [soflyy/wp-all-import-action-reference#65]
I need to set some additional custom fields for products that are no longer in the file, since outofstock is not enough for Woocommerce so I added this code (tried both functions.php in child theme and plugins editor):

```
function wpai_pmxi_delete_post( $ids ){
    foreach($ids as $pid){
        update_post_meta($pid, '_stock', 0);
    }
}
add_action('pmxi_delete_post', 'wpai_pmxi_delete_post', 10, 1);
```

I might need to set some additional info, but wanted to test it out. Tried other actions too, like one for custom field but neither that one works?

**Comment by shazzad** [comment]
> 
> 
> I need to set some additional custom fields for products that are no longer in the file, since outofstock is not enough for Woocommerce so I added this code (tried both functions.php in child theme and plugins editor):
> 
> ```
> function wpai_pmxi_delete_post( $ids ){
>     foreach($ids as $pid){
>         update_post_meta($pid, '_stock', 0);
>     }
> }
> add_action('pmxi_delete_post', 'wpai_pmxi_delete_post', 10, 1);
> ```
> 
> I might need to set some additional info, but wanted to test it out. Tried other actions too, like one for custom field but neither that one works?

This action is only triggered if the post is getting deleted. However, if you have checked any of the following then you might wanna use `pmxi_missing_post` - 
* Instead of deletion, set Custom Field
* Instead of deletion, change post status to Draft

```
function wpai_pmxi_missing_post($pid){
  update_post_meta($pid, '_stock', 0);
}
add_action('pmxi_missing_post', 'wpai_pmxi_missing_post', 10, 1);
```

**Comment by zoltan-ofir** [comment]
thank you
