### ISSUE TITLE
Plugin is creating duplicate images with hyphens

### ISSUE THREAD

**Issue by pirex360** [soflyy/wp-all-import-action-reference#68]
I there, I am using your plugin... but every time I sync by the same csv... all the images are duplicate with ....-X.jpg .

```
filename.jpg = new filename-1,jpg ...
filename-1.jpg = new filename-2.jpg... an so on....
```

I tried every option by your UI in admin panel...but no luck...
I changed the options to ignore the image...and no file is recently uploaded... but I really want if the image was chanced...the new image to be copied to wp with the same name and updated product image.

Can you help?

note: The first product to import works well, but the rest create a new image in gallery with hyphen + number.

**Comment by Marigno** [comment]
Hey @pirex360. Sorry, but we aren't able to handle support via GitHub.

That said, we'd be happy to help! Please submit a support request at http://www.wpallimport.com/support/.
