### ISSUE TITLE
Cannot import serialized data

### ISSUE THREAD

**Issue by avblink** [soflyy/wp-all-import-action-reference#70]
Hi,

One of my fields requires data in a form of serialized string.

`a:9:{s:15:"google_location";s:0:"";s:20:"google_street_number";s:0:"";s:12:"google_route";s:0:"";s:11:"google_city";s:7:"München";s:12:"google_state";s:0:"";s:18:"google_postal_code";s:0:"";s:14:"google_country";s:0:"";s:18:"google_map_country";s:7:"Germany";s:0:"";}`

the field name is `address`. 

I set up custom field name to 'address' and value to '{address[1]}'.

It imports all records but only first record contains serialized field. 
The address field for the rest of the records is blank.

pmxi_custom_field filter shows valid value for the first record only, for the rest it is blank.

Can you please advice.

Thank you

**Comment by avblink** [comment]
Upon further investigation I've found that some rows/records had corrupt serialized string.

However, is there a way to treat the string as a string instead of serialized data?

**Comment by Marigno** [comment]
Hey @avblink. Sorry, we aren't able to handle support via GitHub.

But, we'd be happy to help! Please submit a support request at http://www.wpallimport.com/support/.
