### ISSUE TITLE
Convert xml character encoding to utf-8 before processing starts

### ISSUE THREAD

**Issue by bafrinrealtimeit** [soflyy/wp-all-import-action-reference#8]
I am trying to import xml file which its character encoding is not utf-8 and it is not declared in the file (it is utf-16), how is this possible to change the encoding before import process to avoid not valid file exception? 
(So the file will be 100% uploaded but just before it starts processing it throws this exception)

**There's a problem with your import file
This XML file has errors and is not valid.**

I want to add a cron job to update the imported products automatically so the xml encoding needs to be converted automatically.

I declared the encoding in the xml file, and changed the default encoding to utf-16 and also tried the following code, but none of them fixed the issue
	<?php
add_action('pmxi_before_xml_import', 'before_xml_import', 10, 1);
function utf16_to_utf8($str) {
    $c0 = ord($str[0]);
    $c1 = ord($str[1]);

    if ($c0 == 0xFE && $c1 == 0xFF) {
        $be = true;
    } else if ($c0 == 0xFF && $c1 == 0xFE) {
        $be = false;
    } else {
        return $str;
    }

    $str = substr($str, 2);
    $len = strlen($str);
    $dec = '';
    for ($i = 0; $i < $len; $i += 2) {
        $c = ($be) ? ord($str[$i]) << 8 | ord($str[$i + 1]) : 
                ord($str[$i + 1]) << 8 | ord($str[$i]);
        if ($c >= 0x0001 && $c <= 0x007F) {
            $dec .= chr($c);
        } else if ($c > 0x07FF) {
            $dec .= chr(0xE0 | (($c >> 12) & 0x0F));
            $dec .= chr(0x80 | (($c >>  6) & 0x3F));
            $dec .= chr(0x80 | (($c >>  0) & 0x3F));
        } else {
            $dec .= chr(0xC0 | (($c >>  6) & 0x1F));
            $dec .= chr(0x80 | (($c >>  0) & 0x3F));
        }
    }
    return $dec;
}

function before_xml_import($import_id) {
    $import = new PMXI_Import_Record();
	$import->getById($import_id);
	$path = $import->path;
	$content = utf16_to_utf8(file_get_contents($path));
	unlink($path);
	$handle = fopen($path, 'w');
	fwrite($handle, $content);
	fclose($handle);
}
?>

**Comment by bafrinrealtimeit** [comment]
I found a hack around this problem which I am not happy with so any help would be appreciated.
I added utf16_to_utf8 function to helpers/wp_all_import_get_url.php and after the file is uploaded  open/encode and close it. Now wpallimport can download the xml file with no dramas but if I want to update the plugin my changes will be gone so this is not the ideal solution.

wp_all_import_get_url.php looks like this after my changes

<?php
/**
 * Reading large files from remote server
 * @ $filePath - file URL
 * return local path of copied file
 */
function utf16_to_utf8($str) {
    $c0 = ord($str[0]);
    $c1 = ord($str[1]);

    if ($c0 == 0xFE && $c1 == 0xFF) {
        $be = true;
    } else if ($c0 == 0xFF && $c1 == 0xFE) {
        $be = false;
    } else {
        return $str;
    }

    $str = substr($str, 2);
    $len = strlen($str);
    $dec = '';
    for ($i = 0; $i < $len; $i += 2) {
        $c = ($be) ? ord($str[$i]) << 8 | ord($str[$i + 1]) : 
                ord($str[$i + 1]) << 8 | ord($str[$i]);
        if ($c >= 0x0001 && $c <= 0x007F) {
            $dec .= chr($c);
        } else if ($c > 0x07FF) {
            $dec .= chr(0xE0 | (($c >> 12) & 0x0F));
            $dec .= chr(0x80 | (($c >>  6) & 0x3F));
            $dec .= chr(0x80 | (($c >>  0) & 0x3F));
        } else {
            $dec .= chr(0xC0 | (($c >>  6) & 0x1F));
            $dec .= chr(0x80 | (($c >>  0) & 0x3F));
        }
    }
    return $dec;
}
if (!function_exists('wp_all_import_get_url')) {

    function wp_all_import_get_url($filePath, $targetDir = FALSE, $contentType = FALSE, $contentEncoding = FALSE, $detect = FALSE) {

        $type = $contentType;

        $uploads = wp_upload_dir();

        $targetDir = (!$targetDir) ? wp_all_import_secure_file($uploads['basedir'] . DIRECTORY_SEPARATOR . PMXI_Plugin::UPLOADS_DIRECTORY) : $targetDir;

        $tmpname = wp_unique_filename($targetDir, ($type and strlen(basename($filePath)) < 30) ? basename($filePath) : time());
        $localPath = $targetDir . '/' . urldecode(sanitize_file_name($tmpname)) . ((!$type) ? '.tmp' : '');

        if ($contentEncoding == 'gzip') {
            $file = @fopen($filePath);
        }
        else {
            $file = @fopen($filePath, "rb");
        }

        $is_valid = FALSE;

        if (is_resource($file)) {

            $fp = @fopen($localPath, 'w');
            $first_chunk = TRUE;
            while (!@feof($file)) {
                $chunk = @fread($file, 1024);
                if (!$type and $first_chunk and (strpos($chunk, "<?") !== FALSE or strpos($chunk, "<rss") !== FALSE) or strpos($chunk, "xmlns") !== FALSE) {
                    $type = 'xml';
                }
                elseif (!$type and $first_chunk) {
                    $type = 'csv';
                } // if it's a 1st chunk, then chunk <? symbols to detect XML file
                $first_chunk = FALSE;
                @fwrite($fp, $chunk);
            }
            @fclose($file);
            @fclose($fp);

	$content = utf16_to_utf8(file_get_contents($localPath));
	unlink($localPath);
	$handle = fopen($localPath, 'w');
	fwrite($handle, $content);
	fclose($handle);


            $chunk = new PMXI_Chunk($localPath);

            $is_valid = TRUE;

            if (!empty($chunk->options['element'])) {
                $defaultXpath = "/" . $chunk->options['element'];
            }
            else {
                $is_valid = FALSE;
            }

            if ($is_valid) {

                while ($xml = $chunk->read()) {

                    if (!empty($xml)) {

                        //PMXI_Import_Record::preprocessXml($xml);
                        $xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" . "\n" . $xml;

                        $dom = new DOMDocument('1.0', 'UTF-8');
                        $old = libxml_use_internal_errors(TRUE);
                        $dom->loadXML($xml);
                        libxml_use_internal_errors($old);
                        $xpath = new DOMXPath($dom);
                        if (($elements = $xpath->query($defaultXpath)) and $elements->length) {
                            break;
                        }
                    }
                }

                if (empty($xml)) {
                    $is_valid = FALSE;
                }
            }

            unset($chunk);

        }

        if (!$is_valid) {

            $request = get_file_curl($filePath, $localPath);

            if (!is_wp_error($request)) {

                if (!$type) {
                    if ($contentEncoding == 'gzip') {
                        $file = @fopen($localPath);
                    }
                    else {
                        $file = @fopen($localPath, "rb");
                    }
                    while (!@feof($file)) {
                        $chunk = @fread($file, 1024);
                        if (strpos($chunk, "<?") !== FALSE or strpos($chunk, "<rss") !== FALSE or strpos($chunk, "xmlns") !== FALSE) {
                            $type = 'xml';
                        }
                        else {
                            $type = 'csv';
                        } // if it's a 1st chunk, then chunk <? symbols to detect XML file
                        break;
                    }
                    @fclose($file);
                }
            }
            else {
                return $request;
            }

        }

        if (!preg_match('%\W(' . $type . ')$%i', basename($localPath))) {
            if (@rename($localPath, $localPath . '.' . $type)) {
                $localPath = $localPath . '.' . $type;
            }
        }

        return ($detect) ? array(
            'type' => $type,
            'localPath' => $localPath
        ) : $localPath;
    }
}

**Comment by trey8611** [comment]
Hey @bafrinrealtimeit 

Sorry for the delay on this. 

> I declared the encoding in the xml file, and changed the default encoding to utf-16 and also tried the following code, but none of them fixed the issue

If you declare and use utf-16 encoding in the file, you can import the file - however, you'll need to add the following code snippet to your site:

```
add_filter( 'is_xml_preprocess_enabled', 'wpai_is_xml_preprocess_enabled', 10, 1 );

function wpai_is_xml_preprocess_enabled( $is_enabled ) {
	return false;
}
```

This snippet will need to be added inside your themes (preferably child theme) functions.php file, or in a plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/).

Alternatively, you could create a proxy PHP script that downloads the file, converts the encoding (with your custom function above), then outputs the data (or writes it to a new file). You can point your import to that PHP script via the "Download from URL" option.
