### ISSUE TITLE
User hooks

### ISSUE THREAD

**Issue by tfont** [soflyy/wp-all-import-action-reference#9]
I've created my own hook from a user field connecting through the functions editors. Would be nice to have user hooks though. After and before user creation.

**Comment by trey8611** [comment]
Hey @tfont 

Our hooks work for users as well - for example, [pmxi_saved_post](https://github.com/soflyy/wp-all-import-action-reference/blob/master/all-import/pmxi_saved_post.php) fires when a user is imported, and [wp_all_import_is_post_to_create](https://github.com/soflyy/wp-all-import-action-reference/blob/master/all-import/wp_all_import_is_post_to_create.php) fires just before the user is created.
